<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>be.charleshornick</groupId>
        <artifactId>beyond-the-theory</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>facade-batch</artifactId>

    <name>Primary Adapter - Batch character creation</name>
    <description>A batch adapter to show how failing creation are managed through Result</description>

    <dependencies>
        <dependency>
            <groupId>be.charleshornick</groupId>
            <artifactId>character-creation</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>be.charleshornick</groupId>
            <artifactId>cqs-core</artifactId>
            <version>${project.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>jakarta.inject</groupId>
            <artifactId>jakarta.inject-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jspecify</groupId>
            <artifactId>jspecify</artifactId>
        </dependency>
    </dependencies>
</project>
